### ISSUE TITLE
Discussão sobre o Workflow imposto

### ISSUE THREAD

**Issue by yawner-dev** [ES-PL4-2018/gate-project-pl4#1]
Foi criado o documento de Workflow 

* [Primeira revisão](
https://github.com/ES-PL4-2018/gate-project-pl4/blob/8b88a1f82ae20b797785727f09c845be075abe0e/doc/team-ambiente/Workflow%20GitHub.md) 
* [Segunda revisão](https://github.com/ES-PL4-2018/gate-project-pl4/blob/master/doc/team-ambiente/Workflow%20GitHub.md)

Leiam e discutam vossas dúvidas e possíveis alterações nesta thread.

**Comment by jessicamegane** [comment]
Como funciona um hotfix? Ainda não vi isso em lado nenhum

**Comment by Pmsilva1** [comment]
Hotfixes são para arranjar bugs especificos que passem despercebidos pelas reviews até ao master e que precisam de fix urgente, i.e. security issues, e usando pull requests fica simples de aprovar e testar os fixes. Por isso agora numa etapa inicial, até termos alguma coisa no master, não deve acontecer muito.

**Comment by Gdtav** [comment]
Uma vez que a documentação é um caso particular do projeto, não ajudaria mais à organização haver um branch só para questões de documentação? Assim podíamos ir atualizando/modificando a documentação e lançar tudo numa versão unificada quando se fizesse merge para o  master

**Comment by yawner-dev** [comment]
@Gdtav Ainda seria necessário estar a fazer uma branch para cada equipa. Um dos problemas de se ter uma branch unificada seria:

1. Muitos commits e constantemente estar a fazer push da branch de documentação
2. Estar a receber updates de documentos que não interessam à ti de momento (aka redigir o documento)
3. Potenciais erros de push por estar muitos commits atrás da origem (Ponto 1), o que é confuso.
4. Não interferir no trabalho de outros por acidentes

Acho que por esses motivos é mais interessante estar do jeito que foi definido. Estou aberto a sugestões e se discordam por favor discutam.

**Comment by jmgsoares** [comment]
Deixo uma possível ideia para workflow:
O master é onde se encontra o produto no seu estado mais completo (sendo que neste caso só será atualizado por volta do final de cada sprint com o merge dos branchs de cada equipa)
- Ao inicio da sprint todas as equipas têm o seu respetivo branch com base no master;
- Durante a sprint os elementos das equipas vão fazendo os seus branchs (a partir do branch da sua equipa) consoante as necessidades e quando acabam de desenvolver o trabalho fazem pull request ao brach da sua equipa - sendo este aceite/gerido pelo lead da equipa);
- Quando no final da sprint ou se for decidido antes, o lead da equipa faz pull request ao master e quando for efetuado o merge, atualiza o branch e repete o processo;

A documentação, penso tratar-se de um processo que ocorre para garantir a qualidade do projeto , portanto poderá ser trabalhada a partir do branch da qualidade.

O código desenvolvido pelo development quando "terminado" faz pull request ao branch do testing para ser testado

Fiz 2 documentos com trees de commits durante 1 sprint, um deles mostra uma visão geral do branchs das várias teams, e o outro, uma visão especifica de um branch de uma team;

[git master tree.pdf](https://github.com/ES-PL4-2018/gate-project-pl4/files/2414775/git.master.tree.pdf)
[git team tree.pdf](https://github.com/ES-PL4-2018/gate-project-pl4/files/2414776/git.team.tree.pdf)

**Comment by yawner-dev** [comment]
Foi atualizado o manual de acordo com as sugestões cá feitas.

https://github.com/ES-PL4-2018/gate-project-pl4/blob/master/doc/team-ambiente/Workflow%20GitHub.md
